<?php if ($this->canShowPersonalization()) : ?>
<button id="bt1" onclick="setVisibility('catalog-product-view-product-personalization-content')" class="button btn-product-personalize "  type="button"><span><span><?php echo $this->__('Personalize');?></span></span></button>
<br class="clearfloat" />
<?php echo $this->GetChildHtml('calendar'); ?>
<div id="catalog-product-view-product-personalization-content" class="product-personalization-content">
	<?php echo $this->getChildHtml('product_personalization_form'); ?>
</div>
<script language="JavaScript">
function setVisibility(id) {
	if(document.getElementById('bt1').value=='Hide Layer') {
		document.getElementById('bt1').value = 'Show Layer';
		new Effect.BlindUp($(id));
	} else {
		document.getElementById('bt1').value = 'Hide Layer';
		new Effect.BlindDown($(id));
	}
}
$('catalog-product-view-product-personalization-content').style.display = 'none';
$('product_addtocart_form').enctype="multipart/form-data";


</script>

<br class="clearfloat" />
<?php endif; ?>