<div class="<?php echo $this->getClassName() ?> personal_txt">
 <select class="font-family" onchange="personal_information_.style.fontFamily=this.value">
     <option value="proxima_nova_rgregular" selected="selected"> SELECT FONT STYLE</option>
     <option value="proxima_nova_alt_rgbold">Proxima Bold</option>
     <option value="proxima_nova_rgregular">Proxima Regular</option>
     <option value="source_sans_prosemibold">source sans</option>
     </select>
<br/>
<!---->
<div class="personal_txt_next">
<span class="personal_txt_top">Please select your font color</span>
 
<a href="javascript:void(0)" data-index="Onyx" name="colo"><div class="persColor" style="background:#08100a;"></div></a>

<a href="javascript:void(0)" data-index="OxfordBlue" class="colo" name="colo"><div class="persColor" style="background:#0E0E39;"></div></a>

<a href="javascript:void(0)" data-index="Endeavor" class="colo" name="colo"><div class="persColor" style="background:#254A99;" ></div></a>

<a href="javascript:void(0)" data-index="PineGreen" class="colo" name="colo"><div class="persColor" style="background:#1F917F;"></div></a>

<a href="javascript:void(0)" data-index="Verdegris" class="colo" name="colo"><div class="persColor" style="background:#48B0B8;"></div></a>

<a href="javascript:void(0)" data-index="MandarinOrange" class="colo" name="colo"><div class="persColor" style="background:#891428;"></div></a>

<a href="javascript:void(0)" data-index="Cinnabar" name="colo"><div class="persColor" style="background:#E34830;"></div></a>

<a href="javascript:void(0)" data-index="Bordeaux" class="colo" name="colo"><div class="persColor" style="background:#491B1B;"></div></a>

<a href="javascript:void(0)" data-index="Bronze" class="colo" name="colo"><div class="persColor" style="background:#49351F;" ></div></a>

<a href="javascript:void(0)" data-index="GoldLaser" class="colo" name="colo"><div class="persColor" style="background:#CAB262;"></div></a>

</div>
<div class="kuchb">
    <?php echo $this->getChildHtml() ?></div>
</div>