<div class="<?php echo $this->getClassName() ?> personal_txt">
 <select class="font-family" onchange="personal_information_.style.fontFamily=this.value">
     <option value="proxima_nova_rgregular" selected="selected"> SELECT FONT STYLE</option>
     <option value="proxima_nova_alt_rgbold">Proxima Bold</option>
     <option value="proxima_nova_rgregular">Proxima Regular</option>
     <option value="source_sans_prosemibold">source sans</option>
     </select>
<br/>
<!---->
<div class="personal_txt_next">
<span class="personal_txt_top">Please select your font color</span>

<a href="javascript:void(0)" data-index="Onyx" name="colo"><div style="background:Red;width:13px; height:13px; float:left;margin-right:5px; 
border:solid 1px #f07479;"></div></a>

<a href="javascript:void(0)" data-index="OxfordBlue" class="colo" name="colo"><div style="background:#08100A;width:13px; height:13px; float:left;margin-right:5px; 
border-radius: 4px;"></div></a>

<a href="javascript:void(0)" data-index="Endeavor" class="colo" name="colo"><div style="background:blue;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #5d75b3;" ></div></a>

<a href="javascript:void(0)" data-index="PineGreen" class="colo" name="colo"><div style="background:grey;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #c3c3c3;"></div></a>

<a href="javascript:void(0)" data-index="Verdegris" class="colo" name="colo"><div style="background:yellow;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #fadb5d;"></div></a>

<a href="javascript:void(0)" data-index="MandarinOrange" class="colo" name="colo"><div style="background:black;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #414141;"></div></a>

<a href="javascript:void(0)" data-index="Cinnabar" name="colo"><div style="background:Red;width:13px; height:13px; float:left;margin-right:5px; 
border:solid 1px #f07479;"></div></a>

<a href="javascript:void(0)" data-index="Bordeaux" class="colo" name="colo"><div style="background:Green;width:13px; height:13px; float:left;margin-right:5px; 
border:solid 1px #5cb369;"></div></a>

<a href="javascript:void(0)" data-index="Bronze" class="colo" name="colo"><div style="background:blue;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #5d75b3;" ></div></a>

<a href="javascript:void(0)" data-index="GoldLaser" class="colo" name="colo"><div style="background:grey;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #c3c3c3;"></div></a>

</div>
<div class="kuchb">
    <?php echo $this->getChildHtml() ?></div>
</div>