<div class="<?php echo $this->getClassName() ?> personal_txt">
 <select class="font-family" onchange="personal_information_.style.fontFamily=this.value">
     <option value="proxima_nova_rgregular" selected="selected"> SELECT FONT STYLE</option>
     <option value="proxima_nova_alt_rgbold">Proxima Bold</option>
     <option value="proxima_nova_rgregular">Proxima Regular</option>
     <option value="source_sans_prosemibold">source sans</option>
     </select>
<br/>
<!---->
<div class="personal_txt_next">
<span class="personal_txt_top">Please select your font color</span>
<a href="javascript:void(0)" data-index="Red"  name="colo"><div style="background:Red;width:13px; height:13px; float:left;margin-right:5px; 
border:solid 1px #f07479;"></div></a>
<a href="javascript:void(0)" data-index="Green" class="colo" name="colo"><div style="background:Green;width:13px; height:13px; float:left;margin-right:5px; 
border:solid 1px #5cb369;"></div></a>
<a href="javascript:void(0)"  data-index="Blue" class="colo" name="colo"><div style="background:blue;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #5d75b3;" ></div></a>
<a href="javascript:void(0)"  data-index="grey" class="colo" name="colo"><div style="background:grey;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #c3c3c3;"></div></a>
<a href="javascript:void(0)"  data-index="yellow" class="colo" name="colo"><div style="background:yellow;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #fadb5d;"></div></a>
<a href="javascript:void(0)" data-index="Black" class="colo" name="colo"><div style="background:black;width:13px; height:13px; float:left;margin-right:5px;
border:solid 1px #414141;"></div></a>
</div>
<div class="kuchb">
 <?php echo $this->getChildHtml() ?>
    </div>
 
</div>