<form id="co-discountcode-form" action="">
<fieldset>
	<ul class="form-list">
		<li class="wide">
			<label for="coupon_code"><?php echo $this->__('Have a discount code?Enter it here:')?></label>
			<div class="input-box"><input value="" name="coupon_code" id="coupon_code" class="input-text"></div>
		</li>
	</ul>
</fieldset>
</form>
<div class="buttons-set" id="discountcode-buttons-container">
	<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	<button type="button" class="button" onclick="discountcode.save()"><span><span><?php echo $this->__('Apply') ?></span></span></button>
	<span id="discountcode-please-wait" class="please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	</span>
</div>

<script type="text/javascript">
//<![CDATA[
var discountcode = new Discountcode('co-discountcode-form','<?php echo $this->getUrl('checkoutdiscountcode/index/submit')?>');
//]]>
</script>